### ISSUE TITLE
Make the function work with multiple ICAOs

### ISSUE THREAD

**Issue by rupinr** [RAZERZ/PullFlightData#2]

**Comment by RAZERZ** [comment]
This was the reason I decided to create functions and classes. This way, all you need to do is re-assign the $ICAO and the $airline variables, and then create a new instance of the class and initiate the functions ;). Before, you would have to create a clone of the file and replace the variables. The reason I did this is because some airlines have different bases (SAS, the VA I run, has ESSA, ENGM, and EKCH) and it would make it easier for others as well ;)
